apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-neo4j-connect
  labels:
    app: kafka-neo4j-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-neo4j-connect
  template:
    metadata:
      labels:
        app: kafka-neo4j-connect
    spec:
      containers:
        - name: kafka-neo4j-connect
          image: veedata/kafka-neo4j-connect:latest2
          ports:
            - containerPort: 8083
          env:
            - name: NEO4J_AUTH
              value: "neo4j/project1phase2"
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "kafka-service:29092"
            - name: CONNECT_GROUP_ID
              value: "neo4j-sink-connector"
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/confluent-hub-components"
            - name: NEO4J_HOST
              value: "neo4j-service:7687"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"          
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-neo4j-connect-service
  labels:
    app: kafka-neo4j-connect
spec:
  selector:
    app: kafka-neo4j-connect
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP